language: python
python:
  - "2.7"
script: 
  - "echo Hi world!"
before_deploy:
  - curl "https://pypi.python.org/packages/source/P/PyInstaller/PyInstaller-2.1.tar.gz" >> PyInstaller-2.1.tar.gz
  - tar -xzvf PyInstaller-2.1.tar.gz
  - ls
  - python PyInstaller-2.1/pyinstaller.py mm.spec
  - tar -zcvf mm-linux.tar.gz /dist/mm
  - ls 
deploy:
  provider: releases
  api-key: "a41b873cd065adfcfa07dc0f3cef6c0e0ec6d9a3"
  file: "mm-linux.tar.gz"
  skip_cleanup: true
  on:
    tags: true
    all_branches: true